apiVersion: jenkins.io/v1
kind: Scheduler
metadata:
  name: lh-scheduler
spec:
  lgtm:
    reviewActsAsLgtm: true
  merger:
    mergeMethod: rebase
  plugins:
    entries:
      - label
  postsubmits:
    replace: true
    entries:
    - agent: tekton
      branches:
        entries:
        - master
      name: release
      context: ""
      policy:
        requiredStatusChecks:
          contexts:
            entries:
            - whitesource
    - agent: tekton
      branches:
        entries:
        - master
      cluster: ""
      context: whitesource
      labels: {}
      maxConcurrency: 0
      name: whitesource
      report: false
      runIfChanged: ""
      skipBranches: {}
  presubmits:
    replace: true
    entries:
    - agent: tekton
      alwaysRun: true
      context: pr-build
      name: pr-build
      policy:
        requiredStatusChecks:
          contexts:
            entries:
            - pr-build
            - ghe
            - bbs
            - tekton
            - jenkins
      queries:
      - labels:
          entries:
          - approved
          - lgtm
        missingLabels:
          entries:
          - do-not-merge
          - do-not-merge/hold
          - do-not-merge/work-in-progress
          - needs-ok-to-test
          - needs-rebase
          - needs-security-review
      - labels:
          entries:
            - updatebot
        missingLabels:
          entries:
            - do-not-merge
            - do-not-merge/hold
            - do-not-merge/work-in-progress
            - needs-ok-to-test
            - needs-rebase
            - needs-security-review
      report: true
      rerunCommand: /test pr-build
      trigger: (?m)^/test( all| pr-build),?(s+|$)
    - agent: tekton
      alwaysRun: true
      context: ghe
      name: ghe
      queries:
      - labels:
          entries:
          - approved
          - lgtm
        missingLabels:
          entries:
          - do-not-merge
          - do-not-merge/hold
          - do-not-merge/work-in-progress
          - needs-ok-to-test
          - needs-rebase
          - needs-security-review
      - labels:
          entries:
            - updatebot
        missingLabels:
          entries:
            - do-not-merge
            - do-not-merge/hold
            - do-not-merge/work-in-progress
            - needs-ok-to-test
            - needs-rebase
            - needs-security-review
      report: true
      rerunCommand: /test ghe
      trigger: (?m)^/test( all| bdd| all-gh| ghe),?(s+|$)
    - agent: tekton
      alwaysRun: true
      context: bbs
      name: bbs
      queries:
      - labels:
          entries:
          - approved
          - lgtm
        missingLabels:
          entries:
          - do-not-merge
          - do-not-merge/hold
          - do-not-merge/work-in-progress
          - needs-ok-to-test
          - needs-rebase
          - needs-security-review
      - labels:
          entries:
            - updatebot
        missingLabels:
          entries:
            - do-not-merge
            - do-not-merge/hold
            - do-not-merge/work-in-progress
            - needs-ok-to-test
            - needs-rebase
            - needs-security-review
      report: true
      rerunCommand: /test bbs
      trigger: (?m)^/test( all| bdd| bbs),?(s+|$)
    - agent: tekton
      alwaysRun: true
      context: jenkins
      name: jenkins
      queries:
      - labels:
          entries:
          - approved
          - lgtm
        missingLabels:
          entries:
          - do-not-merge
          - do-not-merge/hold
          - do-not-merge/work-in-progress
          - needs-ok-to-test
          - needs-rebase
          - needs-security-review
      report: true
      rerunCommand: /test jenkins
      trigger: (?m)^/test( all| bdd| jenkins),?(s+|$)
    - agent: tekton
      alwaysRun: true
      context: tekton
      name: tekton
      queries:
        - labels:
            entries:
              - approved
              - lgtm
          missingLabels:
            entries:
              - do-not-merge
              - do-not-merge/hold
              - do-not-merge/work-in-progress
              - needs-ok-to-test
              - needs-rebase
              - needs-security-review
        - labels:
            entries:
              - updatebot
          missingLabels:
            entries:
              - do-not-merge
              - do-not-merge/hold
              - do-not-merge/work-in-progress
              - needs-ok-to-test
              - needs-rebase
              - needs-security-review
      report: true
      rerunCommand: /test tekton
      trigger: (?m)^/test( all| bdd| tekton),?(s+|$)
    - agent: tekton
      alwaysRun: false
      context: gitea
      name: gitea
      queries:
        - labels:
            entries:
              - approved
              - lgtm
          missingLabels:
            entries:
              - do-not-merge
              - do-not-merge/hold
              - do-not-merge/work-in-progress
              - needs-ok-to-test
              - needs-rebase
              - needs-security-review
        - labels:
            entries:
              - updatebot
          missingLabels:
            entries:
              - do-not-merge
              - do-not-merge/hold
              - do-not-merge/work-in-progress
              - needs-ok-to-test
              - needs-rebase
              - needs-security-review
      report: true
      rerunCommand: /test gitea
      trigger: (?m)^/test( all| bdd| gitea),?(s+|$)
    - agent: tekton
      alwaysRun: false
      context: migrate-from-prow
      name: migrate-from-prow
      queries:
        - labels:
            entries:
              - approved
              - lgtm
          missingLabels:
            entries:
              - do-not-merge
              - do-not-merge/hold
              - do-not-merge/work-in-progress
              - needs-ok-to-test
              - needs-rebase
              - needs-security-review
        - labels:
            entries:
              - updatebot
          missingLabels:
            entries:
              - do-not-merge
              - do-not-merge/hold
              - do-not-merge/work-in-progress
              - needs-ok-to-test
              - needs-rebase
              - needs-security-review
      report: true
      rerunCommand: /test migrate-from-prow
      trigger: (?m)^/test migrate-from-prow,?(s+|$)
